# Generated by Django 2.1.5 on 2024-02-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0002_auto_20240217_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userId',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
