# Generated by Django 2.1.5 on 2024-03-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0002_users_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='wallet',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
