# Generated by Django 2.1.5 on 2024-02-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0003_auto_20240217_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='usertype',
            field=models.IntegerField(default=1),
        ),
    ]
