# Generated by Django 2.1.5 on 2024-02-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0005_auto_20240217_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
