# Generated by Django 2.1.5 on 2024-03-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0006_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='itemname',
            field=models.TextField(default=''),
        ),
    ]
