# Generated by Django 2.1.5 on 2024-02-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0006_auto_20240217_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
