# Generated by Django 2.1.5 on 2024-02-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0012_auto_20240217_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='users',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
